# Generated by Django 2.2.6 on 2020-07-13 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('titleimg', models.TextField()),
                ('meta', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='createdAt')),
                ('active', models.CharField(choices=[('draft', 'Черновик'), ('pub', 'Опубликовано')], default='draft', max_length=15)),
                ('body', models.TextField()),
                ('createdAt', models.DateField()),
                ('updateAt', models.DateField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
    ]
