# Generated by Django 2.2.6 on 2020-07-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='titleimg',
            field=models.CharField(max_length=250),
        ),
    ]
